spring.application.name=user-management-service

server.port=8081

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/test
spring.datasource.username=postgres
spring.datasource.password=admin@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable or disable LiveReload (enabled by default) browser changes
spring.devtools.livereload.enabled=true

# Disable restart feature (enabled by default) backend changes
spring.devtools.restart.enabled=true

# JWT settings
jwt.secret=jPI2R8zA8Qw16vdNXRqUsFW5eIpwmTnNOe6pF6Y5e4k=
jwt.expiration=3600000


# Logging configuration
logging.level.org.springframework.web=DEBUG

# PostgreSQL Dialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Rate Limiting
rate-limit.enabled=true
rate-limit.capacity=3
rate-limit.refill-tokens=3
rate-limit.refill-duration-seconds=120
